[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { 
    # Excluir archivos con extensiones comunes
    # Añade más extensiones según sea necesario
    "not": [
      { "field": "Path", "regex": "^/static/.*\\.css$" },
      # Agrega más extensiones o patrones aquí según sea necesario
    ]
  }
